import EctoEnum

defenum NotificationEventType, DEFAULT: "DEFAULT", GENERAL: "GENERAL", LOWONSTOCK: "LOWONSTOCK", OUTOFSTOCK: "OUTOFSTOCK", SKUCHECKUP: "SKUCHECKUP", UNUSED: "UNUSED", CLOSED: "CLOSED", NOLOADED: "NOLOADED", INSIGHT: "INSIGHT", DEMAND: "DEMAND"

defenum MessageStatusType, UNREAD: "UNREAD", READ: "READ"
